name : "test"

## General
seed : 1
device : 0 # CPU
datasets : ["cifar10"]
# mean : [0.5, 0.5, 0.5]
# std : [1., 1., 1.]
aug_type : "light"
task : "denoise"
compute_metrics_repeat : 3
check_val_every_n_epoch : 5
num_images_to_log: 4
metrics: ["ssim", {kernel_size : 3}, "ms_ssim", {kernel_size : 3}, "psnr", {}]
feature_metrics: ["kid", {}, "fid", {}, "msid", {}, ]

## Training parameters
size : 32
model : "unet"
model_params: {}
feature_extractor : "resnet18"
epochs : 40
batch_size : 128

lr : 1e-3
# momentum : 0.9
weight-decay : 1e-4
# model_params : {"num_layers" : 5}