name : "test"

## General
seed : 1
device : null # CPU
datasets : ["cifar10"]
data_mean : [0.5, 0.5, 0.5]
data_std : [0.5, 0.5, 0.5]
aug_type : "light"
task : "denoise"
compute_metrics_repeat : 3
check_val_every_n_epoch : 5
num_images_to_log: 4

## Training parameters
size : 32
model : "unet"
model_params: {}
feature_extractor : "resnet18"
pretrained : False
epochs : 80
batch_size : 512

lr : 0.0003
momentum : 0.9
weight-decay : 0.0001
# model_params : {"num_layers" : 5}