name : "test"

## General
seed : 1
device : 0 # CPU
debug: True
train_dataset: "div2k"
val_dataset: "div2k"
# mean : [0.5, 0.5, 0.5]
# std : [1., 1., 1.]
aug_type : "light"
task : "denoise"
compute_metrics_repeat : 3
check_val_every_n_epoch : 5
num_images_to_log: 4
metrics: ["ssim", {kernel_size : 7}, "ms_ssim", {kernel_size : 7}, "psnr", {}, ]
feature_metrics: ["kid", {}, "fid", {}, "msid", {}, ]

## Training parameters
size : 128
model : "unet"
model_params: {}
epochs : 10
batch_size : 8

phases: {
  "generator": [
    {"ep":[0,8],  "lr":[0,0.1], "mom":0.9, },
    {"ep":[8,24], "lr":[0.1, 0.01], "mode":"cos"},
    {'ep':[24, 30], "lr": 0.001}],
  "discriminator": [
    {"ep":[0,8],  "lr":[0,0.1], "mom":0.9, },
    {"ep":[8,24], "lr":[0.1, 0.01], "mode":"cos"},
    {'ep':[24, 30], "lr": 0.001}],
}

# momentum : 0.9
weight-decay : 1e-4
# model_params : {"num_layers" : 5}