name : cifar100_denoise_light_unet_l1
## General
seed : 1
device : 2 # GPU
datasets : ["cifar100"]
data_mean : [0.0, 0.0, 0.0]
data_std : [1.0, 1.0, 1.00]
aug_type : "light"
task : "denoise"

## Training parameters
size : 28
# arch : "resnet18"
feature_extractor : "resnet18"
epochs : 80
batch_size : 512

lr : 0.003
momentum : 0.9
weight-decay : 0.0001
# model_params : {"num_layers" : 5}