name : cifar10_light_unet
## General
seed : 1
device : 3 # GPU
datasets : ["cifar10"]
data_mean : [0.5, 0.5, 0.5]
data_std : [0.5, 0.5, 0.5]
aug_type : "light"
task : "denoise"

## Training parameters
size : 28
# arch : "resnet18"
feature_extractor : "resnet18"
epochs : 80
batch_size : 128

lr : 0.0003
momentum : 0.9
weight-decay : 0.0001
# model_params : {"num_layers" : 5}