name : CIFAR10_CIFAR100_deblur_lightaug_UNet_L1
## General
seed : 1
device : 1 # GPU
datasets : ["cifar10", "cifar100"]
data_mean : [0.0, 0.0, 0.0]
data_std : [1.0, 1.0, 1.0]
aug_type : "light"
task : "deblur"
compute_metrics_repeat : 3
check_val_every_n_epoch : 5

## Training parameters
size : 32
# arch : "resnet18"
feature_extractor : "resnet18"
epochs : 80
batch_size : 512

lr : 0.001
momentum : 0.9
weight-decay : 0.0001
# model_params : {"num_layers" : 5}