name : test1 # CIFAR10_denoise_lightaug_UNet_L1

## General
seed : 1
device : 0 # CPU
datasets : ["cifar10"]
data_mean : [0.0, 0.0, 0.0]
data_std : [1., 1., 1.]
aug_type : "light"
task : "denoise"
compute_metrics_repeat : 3
check_val_every_n_epoch : 1
num_images_to_log: 4
# metrics: {"ssim" : {kernel_size : 3}, "psnr" :{}}
metrics: '["ssim", {"kernel_size" : 3}, "psnr", {}]'
feature_metrics: '["kid", {}, "fid", {}, "msid", {}]'

## Training parameters
size : 32
model : "unet"
model_params: {}
feature_extractor : "resnet18"
epochs : 80
batch_size : 512

lr : 0.0003
momentum : 0.9
weight-decay : 0.0001