
name : __bsds100_L2
## General
device : 0
train_datasets : [bsds100]
val_datasets: [bsds100,'set5']
task : 
check_val_every_n_epoch : 3
num_images_to_log: 4
metrics: "['ssim', {'kernel_size' : 3},'ms-ssim', {'kernel_size' : 3}, 'psnr', {}, 'tv', {}, 'content', {}, 'style', {}]"
feature_metrics: "['kid', {}, 'fid', {}, 'msid', {}]"
## Training parameters
size : 64
model : 
feature_extractor : 'resnet18'
epochs : 60
batch_size : 256

