
        name : deblur_dncnn_bsds100_L1_MS-SSIM

        ## General
        device : 0
        train_dataset : bsds100
        val_datasets: [bsds100,'set5']
        task : deblur
        check_val_every_n_epoch : 2
        metrics: "['ssim', {}, 'ms-ssim', {}, 'psnr', {}, 'content', {}, 'style', {}, 
                    'mse', {}, 'mae', {}, 'gmsd', {}, 'ms-gmsd', {}, 'vif', {}]"
        feature_metrics: "['kid', {}, 'fid', {}, 'msid', {}]"
        #  'gs', {} NOT INCLUDED YET

        ## Training parameters
        size : 256
        model : dncnn
        feature_extractor : 'inceptionV3'
        epochs : 60
        batch_size : 32

        lr : 1e-3
        weight-decay : 1e-4
        # model_params : {'num_layers' : 5}
        
