
name : denoise_dncnn_medicaldecathlon_L2
## General
device : 0
datasets : [medicaldecathlon]
task : denoise
check_val_every_n_epoch : 3
num_images_to_log: 4
metrics: "['ssim', {}, 'ms-ssim', {}, 'psnr', {}, 'tv', {}, 'content', {}, 'style', {}]"
feature_metrics: "['kid', {}, 'fid', {}, 'msid', {}]"
## Training parameters
size : 256
model : dncnn
feature_extractor : 'resnet18'
epochs : 60
batch_size : 32

