## General
seed : 1
device : null # CPU
datasets : ["mnist"]
data_mean : 0.5 0.5 0.5
data_std : 0.5 0.5 0.5
aug_type : "light"
task : "denoise"

## Training parameters
size : 28
# arch : "resnet18"
feature_exctractor : "resnet18"
epochs : 40
batch_size : 128

lr : 0.0003
momentum : 0.9
weight-decay : 0.0001
# model_params : {"num_layers" : 5}