name : sr_div2k_unet_256_ms-ssim

## General
seed : 1
device : 0 # CPU
debug: False
train_dataset: div2k
val_dataset: div2k
# mean : [0.5, 0.5, 0.5]
# std : [1., 1., 1.1]
aug_type : medium
task : sr
compute_metrics_repeat : 3
check_val_every_n_epoch : 5
num_images_to_log: 4
metrics: [psnr, ssim, ms-ssim, gmsd, ms-gmsd, ms-gmsdc,
          fsim, fsimc, vsi, mdsi, vifp,
          content_vgg16_ap, style_vgg16, lpips, dists, brisque,
]

feature_metrics: [is_metric, is, kid, fid, msid]


## Training parameters
size : 256
criterion : [ms-ssim, 1.0]
model : unet
model_params: {}
# epochs : 10
batch_size : 16

phases:
  {ep: [0, 60], lr: [ 0.001 , 0], mode: cos}

weight-decay : 0
